import type { AICharacterProfile } from './types.js';

/** Ordered career ladder — difficulty ramps with personality variety. */
export const CAREER_OPPONENTS: AICharacterProfile[] = [
  {
    id: 'tung',
    name: 'Tung',
    tier: 'apprentice',
    personality: 'funny',
    accuracy: 0.42,
    risk: 0.18,
    pace: 1.05,
    cueId: 'street',
  },
  {
    id: 'balleeina',
    name: 'Balleeina',
    tier: 'beginner',
    personality: 'calm',
    accuracy: 0.42,
    risk: 0.28,
    pace: 1.08,
    cueId: 'classic',
  },
  {
    id: 'elif',
    name: 'Elif',
    tier: 'beginner',
    personality: 'calm',
    accuracy: 0.48,
    risk: 0.32,
    pace: 1.05,
    cueId: 'street',
  },
  {
    id: 'burak',
    name: 'Burak',
    tier: 'intermediate',
    personality: 'toxic',
    accuracy: 0.58,
    risk: 0.55,
    pace: 0.95,
    cueId: 'pro',
  },
  {
    id: 'deniz',
    name: 'Deniz',
    tier: 'skilled',
    personality: 'silent',
    accuracy: 0.68,
    risk: 0.45,
    pace: 0.85,
    cueId: 'neon',
  },
  {
    id: 'arda',
    name: 'Arda',
    tier: 'advanced',
    personality: 'funny',
    accuracy: 0.76,
    risk: 0.62,
    pace: 0.78,
    cueId: 'carbon',
  },
  {
    id: 'selin',
    name: 'Selin',
    tier: 'expert',
    personality: 'calm',
    accuracy: 0.84,
    risk: 0.58,
    pace: 0.7,
    cueId: 'legend',
  },
  {
    id: 'emir',
    name: 'Emir',
    tier: 'master',
    personality: 'toxic',
    accuracy: 0.92,
    risk: 0.7,
    pace: 0.62,
    cueId: 'legend',
  },
];
