/** Stable logical asset / template IDs (guide §5). */

export const AssetIds = {
  tableMesh: 'env.tableMesh',
  ballMesh: 'env.ballMesh',
  cueMesh: 'env.cueMesh',
  tableFloorTex: 'env.floor.table',
  tungBackdropWallTex: 'env.wall.tungBrick',
  texCueClassic: 'tex.cue.classic',
  texCueStreet: 'tex.cue.street',
  texCuePro: 'tex.cue.pro',
  texCueNeon: 'tex.cue.neon',
  ballCue: 'ball.cue',
  ballEight: 'ball.eight',
  ballSolid: (n: number) => `ball.solid.${n}` as const,
  ballStripe: (n: number) => `ball.stripe.${n}` as const,
  cueStick: 'vfx.cueStick',
  /** Demo finger cursor on table during first-break aim intro. */
  aimIntroFinger: 'vfx.aimIntroFinger',
  ballInHandFinger: 'vfx.ballInHandFinger',
  tutorialDragFinger: 'vfx.tutorialDragFinger',
  debugLine: 'line.debug',
  lineAim: 'line.aim',
  lineGhostObject: 'line.ghostObject',
  lineGhostCue: 'line.ghostCue',
  /** Diffuse map manifest keys under `tex.ball.*` (see AssetManifest). */
  texBall: (n: number) => `tex.ball.${n}` as const,
  texBallCue: 'tex.ball.cue',
  texBallZeroFallback: 'tex.ball.zeroFallback',
  soundCueStrike: 'sound.pool.cueStrike',
  soundPocket: 'sound.pool.pocket',
  soundBallsSettle: 'sound.pool.ballsSettle',
  soundBallBall: 'sound.pool.ballBall',
  /** Sıra rakibe / oyuncuya geçtiğinde (tek seferlik). */
  soundTurnBell: 'sound.ui.turnBell',
  /** Maç içi BGM — `GameEngine` her oyunda `bg_2` / `bg_3` arasından rastgele (`music` olayı, loop). */
  musicBgMatch2: 'sound.ui.bgMatch2',
  musicBgMatch3: 'sound.ui.bgMatch3',
  /** Maç sonu / oyunlar arası ekran (loop). */
  musicBgBetweenGames: 'sound.ui.bgBetweenGames',
  /** Win applause one-shot. */
  soundApplause: 'sound.ui.applause',
  /** Next-match ringing cue (looped in HUD popup). */
  soundPhoneRing: 'sound.ui.phoneRing',
  /** Center reaction beat one-shots (`public/audio/Reaction_{1,2,3}.wav`). */
  soundReaction1: 'sound.ui.reaction1',
  soundReaction2: 'sound.ui.reaction2',
  soundReaction3: 'sound.ui.reaction3',
  /** HUD button click (`public/audio/Click.wav`). */
  soundUiClick: 'sound.ui.click',
  /** Tungo — idle FBX behind table rail. */
  opponentTungPlaceholder: 'char.tungPlaceholder',
  /** Torta Tartaruga — idle FBX behind table rail. */
  opponentTortaPlaceholder: 'char.tortaPlaceholder',
  /** Gattotto Otto — idle FBX behind table rail. */
  opponentGattottoPlaceholder: 'char.gattottoPlaceholder',
  opponentTungoIdleModel: 'model.opponent.tungoIdle',
  opponentGattottoIdleModel: 'model.opponent.gattottoIdle',
  opponentTortaIdleModel: 'model.opponent.tortaIdle',
  opponentIdleSidecarDiffuse: 'tex.opponent.idle.sidecar.diffuse',
  opponentIdleSidecarNormal: 'tex.opponent.idle.sidecar.normal',
  opponentIdleSidecarEmissive: 'tex.opponent.idle.sidecar.emissive',
  uiSoundOn: 'ui.sound.on',
  uiSoundOff: 'ui.sound.off',
  uiVsFlare: 'ui.vs.flare',
  uiMoney: 'ui.money',
  uiChampionRibbonMatch: 'ui.ribbon.championMatch',
  uiChampionRibbonTournament: 'ui.ribbon.championTournament',
  uiPlayCta: 'ui.button.playCta',
  uiPlayAgain: 'ui.button.playAgain',
  uiNextGame: 'ui.button.nextGame',
  uiButtonShop: 'ui.button.shop',
  uiButtonMainMenu: 'ui.button.mainMenu',
  uiYouWon: 'ui.result.youWon',
  uiYouLose: 'ui.result.youLose',
  uiShopBanner: 'ui.shop.banner',
  uiButtonStart: 'ui.button.start',
  uiPowerTrackMuted: 'ui.power.trackMuted',
  uiPowerTrackSpectrum: 'ui.power.trackSpectrum',
  uiButtonPlayLegacy: 'ui.button.playLegacy',
  uiMenuBg: 'ui.menu.bg',
  uiMenuLogo: 'ui.menu.logo',
  uiButtonLeaderboards: 'ui.button.leaderboards',
  uiButtonAchievements: 'ui.button.achievements',
  uiButtonPlayMain: 'ui.button.playMain',
  uiButtonTournamentsMain: 'ui.button.tournamentsMain',
  uiButtonShopMain: 'ui.button.shopMain',
  uiTournamentUpNext: 'ui.tournament.upNext',
  uiTournamentLocked: 'ui.tournament.locked',
  uiNoBall: 'ui.ball.empty',
  uiCueClassicCard: 'ui.cue.classicCard',
  uiCueStreetCard: 'ui.cue.streetCard',
  uiCueProCard: 'ui.cue.proCard',
  uiCueNeonCard: 'ui.cue.neonCard',
  uiWinRookieCup: 'ui.win.rookieCup',
  uiWinProSeries: 'ui.win.proSeries',
  uiWinEliteBrawl: 'ui.win.eliteBrawl',
  uiWinGrandSlam: 'ui.win.grandSlam',
  uiWinCasual: 'ui.win.casual',
  uiBallSprite: (n: number) => `ui.ball.${n}` as const,
} as const;
