import type { AssetManifestEntry } from './AssetTypes.js';

export type { AssetKind, AssetManifestEntry } from './AssetTypes.js';

const tableGlb = 'assets/meshes/Table.glb';

function ballDiffuseEntry(n: number): AssetManifestEntry {
  return {
    id: `tex.ball.${n}`,
    kind: 'texture',
    browserUrl: `textures/balls/${n}.jpg`,
    futureMhsPath: `@Assets/Textures/Ball_${n}`,
    sourceFormat: 'jpg',
    notes: 'Loader tries .jpg/.jpeg/.png and textures/ fallback (no balls subfolder).',
  };
}

const ballDiffuseEntries = Object.fromEntries(
  Array.from({ length: 15 }, (_, i) => {
    const n = i + 1;
    return [`tex.ball.${n}`, ballDiffuseEntry(n)] as const;
  }),
) as Record<string, AssetManifestEntry>;

function ballTemplateEntry(id: string): AssetManifestEntry {
  return {
    id,
    kind: 'template',
    browserUrl: `template://${id}`,
    futureMhsPath: `@Templates/${id}.hstf`,
    notes:
      'Contract: children=[visual.mesh.ball]; components=[Transform, MeshRenderer, BallGameplayMarker]; network=Networked; loading=renderer-factory.',
  };
}

const ballTemplateEntries = Object.fromEntries(
  [
    ['ball.cue', ballTemplateEntry('ball.cue')],
    ['ball.eight', ballTemplateEntry('ball.eight')],
    ...Array.from({ length: 7 }, (_, i) => {
      const n = i + 1;
      return [`ball.solid.${n}`, ballTemplateEntry(`ball.solid.${n}`)] as const;
    }),
    ...Array.from({ length: 7 }, (_, i) => {
      const n = i + 9;
      return [`ball.stripe.${n}`, ballTemplateEntry(`ball.stripe.${n}`)] as const;
    }),
  ] as const,
) as Record<string, AssetManifestEntry>;

const uiBallSpriteEntries = Object.fromEntries(
  Array.from({ length: 15 }, (_, i) => {
    const n = i + 1;
    return [
      `ui.ball.${n}`,
      {
        id: `ui.ball.${n}`,
        kind: 'ui',
        browserUrl: `ui/balls/${n}.png`,
        futureMhsPath: `@UI/Balls/${n}.png`,
        sourceFormat: 'png',
      } satisfies AssetManifestEntry,
    ] as const;
  }),
) as Record<string, AssetManifestEntry>;

export const AssetManifest = {
  'env.tableMesh': {
    id: 'env.tableMesh',
    kind: 'model',
    browserUrl: tableGlb,
    futureMhsPath: '@Templates/table.hstf',
    sourceFormat: 'glb',
    unitScale: 1,
    forwardAxis: '+Z',
    upAxis: '+Y',
    pivot: 'custom',
    collision: 'custom',
    notes: 'Imported table mesh; physics bounds authored in Table.ts',
  },
  'env.ballMesh': {
    id: 'env.ballMesh',
    kind: 'model',
    browserUrl: 'assets/meshes/Ball.glb',
    futureMhsPath: '@Assets/Meshes/Ball',
    sourceFormat: 'glb',
    unitScale: 1,
    forwardAxis: '+Z',
    upAxis: '+Y',
    pivot: 'center',
    collision: 'none',
    notes: 'Optional authored ball mesh; renderer falls back to procedural sphere if missing.',
  },

  'env.cueMesh': {
    id: 'env.cueMesh',
    kind: 'model',
    browserUrl: 'assets/meshes/Cue.fbx',
    futureMhsPath: '@Assets/Meshes/Cue',
    sourceFormat: 'fbx',
    unitScale: 1,
    forwardAxis: '+Y',
    upAxis: '+Y',
    pivot: 'custom',
    collision: 'none',
    notes: 'Pool cue mesh; UV albedo per shop cue in `textures/cues/*.png`.',
  },
  'env.floor.table': {
    id: 'env.floor.table',
    kind: 'texture',
    browserUrl: 'textures/floor/floor.jpg',
    futureMhsPath: '@Assets/Textures/FloorTable',
    sourceFormat: 'jpg',
  },
  'env.wall.tungBrick': {
    id: 'env.wall.tungBrick',
    kind: 'texture',
    browserUrl: 'textures/wall/cartoon-brick.png',
    futureMhsPath: '@Assets/Textures/TungBrickWall',
    sourceFormat: 'png',
  },

  'model.opponent.tungoIdle': {
    id: 'model.opponent.tungoIdle',
    kind: 'model',
    browserUrl: 'opponents/tungo/model/Tungo_Idle.fbx',
    futureMhsPath: '@Assets/Opponents/Tungo/Idle',
    sourceFormat: 'fbx',
    notes: 'Spawned for opponent placeholder in gameplay world.',
  },
  'model.opponent.gattottoIdle': {
    id: 'model.opponent.gattottoIdle',
    kind: 'model',
    browserUrl: 'opponents/gattotto_otto/model/Idle.fbx',
    futureMhsPath: '@Assets/Opponents/GattottoOtto/Idle',
    sourceFormat: 'fbx',
  },
  'model.opponent.tortaIdle': {
    id: 'model.opponent.tortaIdle',
    kind: 'model',
    browserUrl: 'opponents/torta_tartaruga/model/Torta_Idle.fbx',
    futureMhsPath: '@Assets/Opponents/TortaTartaruga/Idle',
    sourceFormat: 'fbx',
  },
  'tex.opponent.idle.sidecar.diffuse': {
    id: 'tex.opponent.idle.sidecar.diffuse',
    kind: 'texture',
    browserUrl: 'Image_0.jpg',
    futureMhsPath: '@Assets/Opponents/Common/IdleSidecar_Diffuse',
    sourceFormat: 'jpg',
    notes: 'Mapped as albedo/diffuse when FBX embeds absolute texture disk paths.',
  },
  'tex.opponent.idle.sidecar.normal': {
    id: 'tex.opponent.idle.sidecar.normal',
    kind: 'texture',
    browserUrl: 'Image_2.jpg',
    futureMhsPath: '@Assets/Opponents/Common/IdleSidecar_Normal',
    sourceFormat: 'jpg',
    notes: 'Mapped to normal slot when sidecar textures are present.',
  },
  'tex.opponent.idle.sidecar.emissive': {
    id: 'tex.opponent.idle.sidecar.emissive',
    kind: 'texture',
    browserUrl: 'Image_3.jpg',
    futureMhsPath: '@Assets/Opponents/Common/IdleSidecar_Emissive',
    sourceFormat: 'jpg',
    notes: 'Mapped to emissive slot when sidecar textures are present.',
  },

  ...ballTemplateEntries,

  'vfx.cueStick': {
    id: 'vfx.cueStick',
    kind: 'template',
    browserUrl: 'template://vfx.cueStick',
    futureMhsPath: '@Templates/cue_stick.hstf',
    notes:
      'Contract: children=[cue.root, cue.tip]; components=[Transform, MeshRenderer]; network=LocalOnly; loading=renderer-factory.',
  },
  'vfx.aimIntroFinger': {
    id: 'vfx.aimIntroFinger',
    kind: 'ui',
    browserUrl: 'ui/hand-cursor-tap.png',
    futureMhsPath: '@UI/hand-cursor-tap.png',
    sourceFormat: 'png',
  },
  'vfx.ballInHandFinger': {
    id: 'vfx.ballInHandFinger',
    kind: 'ui',
    browserUrl: 'ui/hand-cursor-tap.png',
    futureMhsPath: '@UI/hand-cursor-tap.png',
    sourceFormat: 'png',
  },
  'vfx.tutorialDragFinger': {
    id: 'vfx.tutorialDragFinger',
    kind: 'ui',
    browserUrl: 'ui/hand-cursor-tap-flipped.png',
    futureMhsPath: '@UI/hand-cursor-tap-flipped.png',
    sourceFormat: 'png',
  },
  'line.aim': {
    id: 'line.aim',
    kind: 'template',
    browserUrl: 'template://line.aim',
    futureMhsPath: '@Templates/line_aim.hstf',
    notes:
      'Contract: children=[line.segment*]; components=[Transform, LineRenderer]; network=LocalOnly; loading=renderer-factory.',
  },
  'line.ghostObject': {
    id: 'line.ghostObject',
    kind: 'template',
    browserUrl: 'template://line.ghostObject',
    futureMhsPath: '@Templates/line_ghost_object.hstf',
    notes:
      'Contract: children=[line.segment*]; components=[Transform, LineRenderer]; network=LocalOnly; loading=renderer-factory.',
  },
  'line.ghostCue': {
    id: 'line.ghostCue',
    kind: 'template',
    browserUrl: 'template://line.ghostCue',
    futureMhsPath: '@Templates/line_ghost_cue.hstf',
    notes:
      'Contract: children=[line.segment*]; components=[Transform, LineRenderer]; network=LocalOnly; loading=renderer-factory.',
  },
  'line.debug': {
    id: 'line.debug',
    kind: 'template',
    browserUrl: 'template://line.debug',
    futureMhsPath: '@Templates/line_debug.hstf',
    notes:
      'Contract: children=[line.segment*]; components=[Transform, LineRenderer]; network=LocalOnly; loading=renderer-factory.',
  },
  'char.tungPlaceholder': {
    id: 'char.tungPlaceholder',
    kind: 'template',
    browserUrl: 'template://char.tungPlaceholder',
    futureMhsPath: '@Templates/opp_tungo_placeholder.hstf',
    notes:
      'Contract: children=[opponent.idle.rig, env.wall.backdrop?]; components=[Transform, SkinnedMeshRenderer, Animator?]; network=LocalOnly; sidecar=[tex.opponent.idle.sidecar.diffuse->albedo, tex.opponent.idle.sidecar.normal->normal, tex.opponent.idle.sidecar.emissive->emissive].',
  },
  'char.tortaPlaceholder': {
    id: 'char.tortaPlaceholder',
    kind: 'template',
    browserUrl: 'template://char.tortaPlaceholder',
    futureMhsPath: '@Templates/opp_torta_placeholder.hstf',
    notes:
      'Contract: children=[opponent.idle.rig, env.wall.backdrop?]; components=[Transform, SkinnedMeshRenderer, Animator?]; network=LocalOnly; sidecar=[tex.opponent.idle.sidecar.diffuse->albedo, tex.opponent.idle.sidecar.normal->normal, tex.opponent.idle.sidecar.emissive->emissive].',
  },
  'char.gattottoPlaceholder': {
    id: 'char.gattottoPlaceholder',
    kind: 'template',
    browserUrl: 'template://char.gattottoPlaceholder',
    futureMhsPath: '@Templates/opp_gattotto_placeholder.hstf',
    notes:
      'Contract: children=[opponent.idle.rig, env.wall.backdrop?]; components=[Transform, SkinnedMeshRenderer, Animator?]; network=LocalOnly; sidecar=[tex.opponent.idle.sidecar.diffuse->albedo, tex.opponent.idle.sidecar.normal->normal, tex.opponent.idle.sidecar.emissive->emissive].',
  },

  'tex.cue.classic': {
    id: 'tex.cue.classic',
    kind: 'texture',
    browserUrl: 'textures/cues/classic.png',
    futureMhsPath: '@Assets/Textures/CueClassic',
    sourceFormat: 'png',
  },
  'tex.cue.street': {
    id: 'tex.cue.street',
    kind: 'texture',
    browserUrl: 'textures/cues/street.png',
    futureMhsPath: '@Assets/Textures/CueStreet',
    sourceFormat: 'png',
  },
  'tex.cue.pro': {
    id: 'tex.cue.pro',
    kind: 'texture',
    browserUrl: 'textures/cues/pro.png',
    futureMhsPath: '@Assets/Textures/CuePro',
    sourceFormat: 'png',
  },
  'tex.cue.neon': {
    id: 'tex.cue.neon',
    kind: 'texture',
    browserUrl: 'textures/cues/neon.png',
    futureMhsPath: '@Assets/Textures/CueNeon',
    sourceFormat: 'png',
  },

  ...ballDiffuseEntries,

  'tex.ball.cue': {
    id: 'tex.ball.cue',
    kind: 'texture',
    browserUrl: 'textures/balls/cue.jpg',
    futureMhsPath: '@Assets/Textures/Ball_cue',
    sourceFormat: 'jpg',
    notes: 'Cue ball diffuse; same fallback rules as tex.ball.*',
  },
  /** Legacy numbered `0.jpeg` / `0.jpg` cue art under `textures/balls/`. */
  'tex.ball.zeroFallback': {
    id: 'tex.ball.zeroFallback',
    kind: 'texture',
    browserUrl: 'textures/balls/0.jpg',
    futureMhsPath: '@Assets/Textures/Ball_0',
    sourceFormat: 'jpg',
    notes: 'Used only if tex.ball.cue fails to load.',
  },

  'ui.opponent.tung.avatar': {
    id: 'ui.opponent.tung.avatar',
    kind: 'ui',
    browserUrl: 'opponents/tung/hud/tung_avatar.png',
    futureMhsPath: '@UI/Opponents/TungAvatar.png',
    sourceFormat: 'png',
    notes: 'HUD opponent portrait',
  },

  'ui.opponent.tung.reaction.happy': {
    id: 'ui.opponent.tung.reaction.happy',
    kind: 'ui',
    browserUrl: 'opponents/tung/reactions/tung_happy.png',
    futureMhsPath: '@UI/Opponents/TungReactions/Happy.png',
    sourceFormat: 'png',
  },
  'ui.opponent.tung.reaction.crazyLaugh': {
    id: 'ui.opponent.tung.reaction.crazyLaugh',
    kind: 'ui',
    browserUrl: 'opponents/tung/reactions/tung_crazy_laugh.png',
    futureMhsPath: '@UI/Opponents/TungReactions/CrazyLaugh.png',
    sourceFormat: 'png',
  },
  'ui.opponent.tung.reaction.laugh': {
    id: 'ui.opponent.tung.reaction.laugh',
    kind: 'ui',
    browserUrl: 'opponents/tung/reactions/tung_laugh.png',
    futureMhsPath: '@UI/Opponents/TungReactions/Laugh.png',
    sourceFormat: 'png',
  },
  'ui.opponent.tung.reaction.angry': {
    id: 'ui.opponent.tung.reaction.angry',
    kind: 'ui',
    browserUrl: 'opponents/tung/reactions/tung_angry.png',
    futureMhsPath: '@UI/Opponents/TungReactions/Angry.png',
    sourceFormat: 'png',
  },
  'ui.opponent.tung.reaction.sad': {
    id: 'ui.opponent.tung.reaction.sad',
    kind: 'ui',
    browserUrl: 'opponents/tung/reactions/tung_sad.png',
    futureMhsPath: '@UI/Opponents/TungReactions/Sad.png',
    sourceFormat: 'png',
  },

  'ui.opponent.tungo.avatar': {
    id: 'ui.opponent.tungo.avatar',
    kind: 'ui',
    browserUrl: 'opponents/tungo/hud/avatar.png',
    futureMhsPath: '@UI/Opponents/TungoAvatar.png',
    sourceFormat: 'png',
    notes: 'HUD opponent portrait (Tungo).',
  },
  'ui.opponent.tungo.reaction.ball': {
    id: 'ui.opponent.tungo.reaction.ball',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_Ball.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/Ball.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.tungo.reaction.cry': {
    id: 'ui.opponent.tungo.reaction.cry',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_Cry.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/Cry.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.tungo.reaction.lastBall': {
    id: 'ui.opponent.tungo.reaction.lastBall',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_LastBalljpg.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/LastBall.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.tungo.reaction.laught': {
    id: 'ui.opponent.tungo.reaction.laught',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_Laught.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/Laught.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.tungo.reaction.scary': {
    id: 'ui.opponent.tungo.reaction.scary',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_Scary.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/Scary.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.tungo.reaction.smile': {
    id: 'ui.opponent.tungo.reaction.smile',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_Smile.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/Smile.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.tungo.reaction.time': {
    id: 'ui.opponent.tungo.reaction.time',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_Time.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/Time.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.tungo.reaction.time2': {
    id: 'ui.opponent.tungo.reaction.time2',
    kind: 'ui',
    browserUrl: 'opponents/tungo/reactions/Tungo_Time2.jpg',
    futureMhsPath: '@UI/Opponents/TungoReactions/Time2.jpg',
    sourceFormat: 'jpg',
  },

  'ui.opponent.torta_tartaruga.avatar': {
    id: 'ui.opponent.torta_tartaruga.avatar',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/hud/avatar.png',
    futureMhsPath: '@UI/Opponents/TortaTartarugaAvatar.png',
    sourceFormat: 'png',
    notes: 'HUD portrait — Torta Tartaruga.',
  },
  'ui.opponent.torta_tartaruga.reaction.ball': {
    id: 'ui.opponent.torta_tartaruga.reaction.ball',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/Ball.jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/Ball.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.torta_tartaruga.reaction.cry': {
    id: 'ui.opponent.torta_tartaruga.reaction.cry',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/Cry.jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/Cry.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.torta_tartaruga.reaction.lastBall': {
    id: 'ui.opponent.torta_tartaruga.reaction.lastBall',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/LastBall (2).jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/LastBall.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.torta_tartaruga.reaction.laught': {
    id: 'ui.opponent.torta_tartaruga.reaction.laught',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/Laught.jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/Laught.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.torta_tartaruga.reaction.scary': {
    id: 'ui.opponent.torta_tartaruga.reaction.scary',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/Scary.jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/Scary.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.torta_tartaruga.reaction.smile': {
    id: 'ui.opponent.torta_tartaruga.reaction.smile',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/Smile.jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/Smile.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.torta_tartaruga.reaction.time': {
    id: 'ui.opponent.torta_tartaruga.reaction.time',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/Time.jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/Time.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.torta_tartaruga.reaction.time2': {
    id: 'ui.opponent.torta_tartaruga.reaction.time2',
    kind: 'ui',
    browserUrl: 'opponents/torta_tartaruga/reactions/Time.jpg',
    futureMhsPath: '@UI/Opponents/TortaTartarugaReactions/Time2.jpg',
    sourceFormat: 'jpg',
  },

  'ui.opponent.gattotto_otto.avatar': {
    id: 'ui.opponent.gattotto_otto.avatar',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/hud/avatar.png',
    futureMhsPath: '@UI/Opponents/GattottoOttoAvatar.png',
    sourceFormat: 'png',
    notes: 'Gattotto Otto — career step between Tungo and Torta.',
  },
  'ui.opponent.gattotto_otto.reaction.ball': {
    id: 'ui.opponent.gattotto_otto.reaction.ball',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/Ball.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/Ball.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.gattotto_otto.reaction.cry': {
    id: 'ui.opponent.gattotto_otto.reaction.cry',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/Cry.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/Cry.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.gattotto_otto.reaction.lastBall': {
    id: 'ui.opponent.gattotto_otto.reaction.lastBall',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/LastBall.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/LastBall.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.gattotto_otto.reaction.laught': {
    id: 'ui.opponent.gattotto_otto.reaction.laught',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/Laught.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/Laught.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.gattotto_otto.reaction.scary': {
    id: 'ui.opponent.gattotto_otto.reaction.scary',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/Scary.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/Scary.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.gattotto_otto.reaction.smile': {
    id: 'ui.opponent.gattotto_otto.reaction.smile',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/Smile.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/Smile.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.gattotto_otto.reaction.time': {
    id: 'ui.opponent.gattotto_otto.reaction.time',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/Time.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/Time.jpg',
    sourceFormat: 'jpg',
  },
  'ui.opponent.gattotto_otto.reaction.time2': {
    id: 'ui.opponent.gattotto_otto.reaction.time2',
    kind: 'ui',
    browserUrl: 'opponents/gattotto_otto/reactions/Time.jpg',
    futureMhsPath: '@UI/Opponents/GattottoReactions/Time2.jpg',
    sourceFormat: 'jpg',
  },

  'ui.opponent.balleeina.avatar': {
    id: 'ui.opponent.balleeina.avatar',
    kind: 'ui',
    browserUrl: 'opponents/balleeina/hud/avatar.png',
    futureMhsPath: '@UI/Opponents/BalleeinaAvatar.png',
    sourceFormat: 'png',
    notes: 'If missing, HUD falls back to generic avatar.',
  },

  'ui.avatar.genericOpponent': {
    id: 'ui.avatar.genericOpponent',
    kind: 'ui',
    browserUrl: 'avatars/opp.svg',
    futureMhsPath: '@UI/Avatars/GenericOpponent.svg',
    sourceFormat: 'svg',
    notes: 'SVG in browser; MHS may swap for raster.',
  },
  'ui.avatar.player': {
    id: 'ui.avatar.player',
    kind: 'ui',
    browserUrl: 'avatars/me.svg',
    futureMhsPath: '@UI/Avatars/Player.svg',
    sourceFormat: 'svg',
    notes: 'SVG in browser',
  },

  'ui.modeselect.cup.rookie': {
    id: 'ui.modeselect.cup.rookie',
    kind: 'ui',
    browserUrl: 'ui/cup_rookie_charge.png',
    futureMhsPath: '@UI/cup_rookie_charge.png',
    sourceFormat: 'png',
    notes: 'Tournament mode-select trophy (Rookie Charge / ROOKIE CUP).',
  },
  'ui.modeselect.cup.pro': {
    id: 'ui.modeselect.cup.pro',
    kind: 'ui',
    browserUrl: 'ui/cup_pro_series.png',
    futureMhsPath: '@UI/cup_pro_series.png',
    sourceFormat: 'png',
    notes: 'Tournament mode-select trophy (Pro Series).',
  },
  'ui.modeselect.cup.elite': {
    id: 'ui.modeselect.cup.elite',
    kind: 'ui',
    browserUrl: 'ui/cup_elite_brawl.png',
    futureMhsPath: '@UI/cup_elite_brawl.png',
    sourceFormat: 'png',
    notes: 'Tournament mode-select trophy (Elite Brawl).',
  },
  'ui.modeselect.cup.grandslam': {
    id: 'ui.modeselect.cup.grandslam',
    kind: 'ui',
    browserUrl: 'ui/cup_grand_slam.png',
    futureMhsPath: '@UI/cup_grand_slam.png',
    sourceFormat: 'png',
    notes: 'Tournament mode-select trophy (Grand Slam / Masters).',
  },

  'ui.sound.on': {
    id: 'ui.sound.on',
    kind: 'ui',
    browserUrl: 'ui/sound.png',
    futureMhsPath: '@UI/sound.png',
    sourceFormat: 'png',
  },
  'ui.sound.off': {
    id: 'ui.sound.off',
    kind: 'ui',
    browserUrl: 'ui/sound_off.png',
    futureMhsPath: '@UI/sound_off.png',
    sourceFormat: 'png',
  },
  'ui.vs.flare': {
    id: 'ui.vs.flare',
    kind: 'ui',
    browserUrl: 'ui/vs.png',
    futureMhsPath: '@UI/vs.png',
    sourceFormat: 'png',
  },
  'ui.money': {
    id: 'ui.money',
    kind: 'ui',
    browserUrl: 'ui/money.png',
    futureMhsPath: '@UI/money.png',
    sourceFormat: 'png',
  },
  'ui.ribbon.championMatch': {
    id: 'ui.ribbon.championMatch',
    kind: 'ui',
    browserUrl: 'ui/champion_match.png',
    futureMhsPath: '@UI/champion_match.png',
    sourceFormat: 'png',
  },
  'ui.ribbon.championTournament': {
    id: 'ui.ribbon.championTournament',
    kind: 'ui',
    browserUrl: 'ui/champion_tournament.png',
    futureMhsPath: '@UI/champion_tournament.png',
    sourceFormat: 'png',
  },
  'ui.button.playCta': {
    id: 'ui.button.playCta',
    kind: 'ui',
    browserUrl: 'ui/Button_Play_new.png',
    futureMhsPath: '@UI/Button_Play_new.png',
    sourceFormat: 'png',
  },
  'ui.button.playAgain': {
    id: 'ui.button.playAgain',
    kind: 'ui',
    browserUrl: 'ui/play_again.png',
    futureMhsPath: '@UI/play_again.png',
    sourceFormat: 'png',
  },
  'ui.button.nextGame': {
    id: 'ui.button.nextGame',
    kind: 'ui',
    browserUrl: 'ui/next-game.png',
    futureMhsPath: '@UI/next-game.png',
    sourceFormat: 'png',
  },
  'ui.button.shop': {
    id: 'ui.button.shop',
    kind: 'ui',
    browserUrl: 'ui/button_shop.png',
    futureMhsPath: '@UI/button_shop.png',
    sourceFormat: 'png',
  },
  'ui.button.mainMenu': {
    id: 'ui.button.mainMenu',
    kind: 'ui',
    browserUrl: 'ui/button_mainmenu.png',
    futureMhsPath: '@UI/button_mainmenu.png',
    sourceFormat: 'png',
  },
  'ui.result.youWon': {
    id: 'ui.result.youWon',
    kind: 'ui',
    browserUrl: 'ui/youwon.png',
    futureMhsPath: '@UI/youwon.png',
    sourceFormat: 'png',
  },
  'ui.result.youLose': {
    id: 'ui.result.youLose',
    kind: 'ui',
    browserUrl: 'ui/youlose.png',
    futureMhsPath: '@UI/youlose.png',
    sourceFormat: 'png',
  },
  'ui.shop.banner': {
    id: 'ui.shop.banner',
    kind: 'ui',
    browserUrl: 'ui/shop_brainrot.png',
    futureMhsPath: '@UI/shop_brainrot.png',
    sourceFormat: 'png',
  },
  'ui.button.start': {
    id: 'ui.button.start',
    kind: 'ui',
    browserUrl: 'ui/button-start.png',
    futureMhsPath: '@UI/button-start.png',
    sourceFormat: 'png',
  },
  'ui.power.trackMuted': {
    id: 'ui.power.trackMuted',
    kind: 'ui',
    browserUrl: 'ui/power-meter/track-muted.png',
    futureMhsPath: '@UI/power-meter/track-muted.png',
    sourceFormat: 'png',
  },
  'ui.power.trackSpectrum': {
    id: 'ui.power.trackSpectrum',
    kind: 'ui',
    browserUrl: 'ui/power-meter/track-spectrum.png',
    futureMhsPath: '@UI/power-meter/track-spectrum.png',
    sourceFormat: 'png',
  },
  'ui.button.playLegacy': {
    id: 'ui.button.playLegacy',
    kind: 'ui',
    browserUrl: 'ui/button_play.png',
    futureMhsPath: '@UI/button_play.png',
    sourceFormat: 'png',
  },
  'ui.menu.bg': {
    id: 'ui.menu.bg',
    kind: 'ui',
    browserUrl: 'ui/bg.jpg',
    futureMhsPath: '@UI/bg.jpg',
    sourceFormat: 'jpg',
  },
  'ui.menu.logo': {
    id: 'ui.menu.logo',
    kind: 'ui',
    browserUrl: 'ui/8ballslogo.png',
    futureMhsPath: '@UI/8ballslogo.png',
    sourceFormat: 'png',
  },
  'ui.button.leaderboards': {
    id: 'ui.button.leaderboards',
    kind: 'ui',
    browserUrl: 'ui/button_leaderboards.png',
    futureMhsPath: '@UI/button_leaderboards.png',
    sourceFormat: 'png',
  },
  'ui.button.achievements': {
    id: 'ui.button.achievements',
    kind: 'ui',
    browserUrl: 'ui/button_achivement.png',
    futureMhsPath: '@UI/button_achivement.png',
    sourceFormat: 'png',
  },
  'ui.button.playMain': {
    id: 'ui.button.playMain',
    kind: 'ui',
    browserUrl: 'ui/Button_Play_new.png',
    futureMhsPath: '@UI/Button_Play_new.png',
    sourceFormat: 'png',
  },
  'ui.button.tournamentsMain': {
    id: 'ui.button.tournamentsMain',
    kind: 'ui',
    browserUrl: 'ui/Button_Tournaments_new.png',
    futureMhsPath: '@UI/Button_Tournaments_new.png',
    sourceFormat: 'png',
  },
  'ui.button.shopMain': {
    id: 'ui.button.shopMain',
    kind: 'ui',
    browserUrl: 'ui/Button_Shop_new.png',
    futureMhsPath: '@UI/Button_Shop_new.png',
    sourceFormat: 'png',
  },
  'ui.tournament.upNext': {
    id: 'ui.tournament.upNext',
    kind: 'ui',
    browserUrl: 'ui/up-next.png',
    futureMhsPath: '@UI/up-next.png',
    sourceFormat: 'png',
  },
  'ui.tournament.locked': {
    id: 'ui.tournament.locked',
    kind: 'ui',
    browserUrl: 'ui/locked.png',
    futureMhsPath: '@UI/locked.png',
    sourceFormat: 'png',
  },
  'ui.ball.empty': {
    id: 'ui.ball.empty',
    kind: 'ui',
    browserUrl: 'ui/no-ball.png',
    futureMhsPath: '@UI/no-ball.png',
    sourceFormat: 'png',
  },
  ...uiBallSpriteEntries,
  'ui.cue.classicCard': {
    id: 'ui.cue.classicCard',
    kind: 'ui',
    browserUrl: 'ui/cue_classic.png',
    futureMhsPath: '@UI/cue_classic.png',
    sourceFormat: 'png',
  },
  'ui.cue.streetCard': {
    id: 'ui.cue.streetCard',
    kind: 'ui',
    browserUrl: 'ui/cue_street_maple.png',
    futureMhsPath: '@UI/cue_street_maple.png',
    sourceFormat: 'png',
  },
  'ui.cue.proCard': {
    id: 'ui.cue.proCard',
    kind: 'ui',
    browserUrl: 'ui/cue_pro_fiber.png',
    futureMhsPath: '@UI/cue_pro_fiber.png',
    sourceFormat: 'png',
  },
  'ui.cue.neonCard': {
    id: 'ui.cue.neonCard',
    kind: 'ui',
    browserUrl: 'ui/cue_neon_glow.png',
    futureMhsPath: '@UI/cue_neon_glow.png',
    sourceFormat: 'png',
  },
  'ui.win.rookieCup': {
    id: 'ui.win.rookieCup',
    kind: 'ui',
    browserUrl: 'ui/Win_RookieCup.png',
    futureMhsPath: '@UI/Win_RookieCup.png',
    sourceFormat: 'png',
  },
  'ui.win.proSeries': {
    id: 'ui.win.proSeries',
    kind: 'ui',
    browserUrl: 'ui/Win_ProSeries.png',
    futureMhsPath: '@UI/Win_ProSeries.png',
    sourceFormat: 'png',
  },
  'ui.win.eliteBrawl': {
    id: 'ui.win.eliteBrawl',
    kind: 'ui',
    browserUrl: 'ui/Win_EliteBrawl.png',
    futureMhsPath: '@UI/Win_EliteBrawl.png',
    sourceFormat: 'png',
  },
  'ui.win.grandSlam': {
    id: 'ui.win.grandSlam',
    kind: 'ui',
    browserUrl: 'ui/Win_GrandSlam.png',
    futureMhsPath: '@UI/Win_GrandSlam.png',
    sourceFormat: 'png',
  },
  'ui.win.casual': {
    id: 'ui.win.casual',
    kind: 'ui',
    browserUrl: 'ui/Win_Casual.png',
    futureMhsPath: '@UI/Win_Casual.png',
    sourceFormat: 'png',
  },

  'sound.pool.cueStrike': {
    id: 'sound.pool.cueStrike',
    kind: 'audio',
    browserUrl: 'audio/initial_hit.ogg',
    futureMhsPath: '@Assets/Audio/CueStrike',
    sourceFormat: 'ogg',
    notes: 'public/audio/initial_hit.ogg; adapter falls back to .mp3/.wav.',
  },
  'sound.pool.pocket': {
    id: 'sound.pool.pocket',
    kind: 'audio',
    browserUrl: 'audio/ball_interaction.ogg',
    futureMhsPath: '@Assets/Audio/Pocket',
    sourceFormat: 'ogg',
    notes: 'public/audio/ball_interaction.ogg when a ball is pocketed.',
  },
  'sound.pool.ballsSettle': {
    id: 'sound.pool.ballsSettle',
    kind: 'audio',
    browserUrl: 'audio/ball_interaction.ogg',
    futureMhsPath: '@Assets/Audio/BallsSettle',
    sourceFormat: 'ogg',
    notes: 'Same clip as pocket until a dedicated settle asset exists.',
  },
  'sound.pool.ballBall': {
    id: 'sound.pool.ballBall',
    kind: 'audio',
    browserUrl: 'audio/ball_interaction.ogg',
    futureMhsPath: '@Assets/Audio/BallBall',
    sourceFormat: 'ogg',
    notes: 'Ball–ball contact; counted in CollisionSystem, sounds from GameEngine.',
  },
  'sound.ui.bgMatch2': {
    id: 'sound.ui.bgMatch2',
    kind: 'audio',
    browserUrl: 'audio/bg_2.ogg',
    futureMhsPath: '@Assets/Audio/BgMatch2',
    sourceFormat: 'ogg',
    notes: 'Looping in-match BGM (50% vs bg_3 per match).',
  },
  'sound.ui.bgMatch3': {
    id: 'sound.ui.bgMatch3',
    kind: 'audio',
    browserUrl: 'audio/bg_3.ogg',
    futureMhsPath: '@Assets/Audio/BgMatch3',
    sourceFormat: 'ogg',
    notes: 'Looping in-match BGM (50% vs bg_2 per match).',
  },
  'sound.ui.bgBetweenGames': {
    id: 'sound.ui.bgBetweenGames',
    kind: 'audio',
    browserUrl: 'audio/bg_betweengames.ogg',
    futureMhsPath: '@Assets/Audio/BgBetweenGames',
    sourceFormat: 'ogg',
    notes: 'Looping between matches (MatchEnd overlay).',
  },
  'sound.ui.applause': {
    id: 'sound.ui.applause',
    kind: 'audio',
    browserUrl: 'audio/applause.ogg',
    futureMhsPath: '@Assets/Audio/Applause',
    sourceFormat: 'ogg',
    notes: 'One-shot applause on player victory.',
  },
  'sound.ui.phoneRing': {
    id: 'sound.ui.phoneRing',
    kind: 'audio',
    browserUrl: 'audio/phonering.ogg',
    futureMhsPath: '@Assets/Audio/PhoneRing',
    sourceFormat: 'ogg',
    notes: 'Looped while searching for next opponent.',
  },
  'sound.ui.turnBell': {
    id: 'sound.ui.turnBell',
    kind: 'audio',
    browserUrl: 'audio/bell.wav',
    futureMhsPath: '@Assets/Audio/TurnBell',
    sourceFormat: 'wav',
    notes: 'Played when turn passes to the other player.',
  },

  'sound.ui.reaction1': {
    id: 'sound.ui.reaction1',
    kind: 'audio',
    browserUrl: 'audio/Reaction_1.wav',
    futureMhsPath: '@Assets/Audio/Reaction_1',
    sourceFormat: 'wav',
    notes: 'Center opponent reaction beat (variant 1).',
  },
  'sound.ui.reaction2': {
    id: 'sound.ui.reaction2',
    kind: 'audio',
    browserUrl: 'audio/Reaction_2.wav',
    futureMhsPath: '@Assets/Audio/Reaction_2',
    sourceFormat: 'wav',
    notes: 'Center opponent reaction beat (variant 2).',
  },
  'sound.ui.reaction3': {
    id: 'sound.ui.reaction3',
    kind: 'audio',
    browserUrl: 'audio/Reaction_3.wav',
    futureMhsPath: '@Assets/Audio/Reaction_3',
    sourceFormat: 'wav',
    notes: 'Center opponent reaction beat (variant 3).',
  },
  'sound.ui.click': {
    id: 'sound.ui.click',
    kind: 'audio',
    browserUrl: 'audio/Click.wav',
    futureMhsPath: '@Assets/Audio/Click',
    sourceFormat: 'wav',
    notes: 'HUD / UI button click.',
  },
} as const satisfies Record<string, AssetManifestEntry>;

export type AssetManifestKey = keyof typeof AssetManifest;
